language: cpp
dist: bionic
jobs:
  include:
    - addons:
        apt:
          packages:
            - libboost-dev
      install:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release
        - make -j$(nproc)
      script:
        - cd ..
        - scripts/runperf.sh ebpf-samples zoneCrab
    - services: docker
      script: docker build .
